#!/bin/bash

sudo apt-get update && sudo apt-get -y install docker.io

# move docker location to /mnt/

sleep 2

sudo bash

export EPHEMERAL="/mnt"
mkdir $EPHEMERAL/tmp/

# export EPHERMERAL="/media/ephemeral/"

echo 'export TMPDIR='$EPHEMERAL'/tmp/' >> /etc/default/docker.io
echo 'export DOCKER_OPTS="-g='$EPHEMERAL'/docker"' >> /etc/default/docker.io

sleep 2

/usr/sbin/service docker.io restart

sleep 4

export DATADIR=/mnt/awe-client/
mkdir -p ${DATADIR}
/usr/bin/docker run -d --name awe-client -v /var/run/docker.sock:/var/run/docker.sock -v ${DATADIR}:${DATADIR}  mgrast/awe /gopath/bin/awe-client --data=${DATADIR}/data --logs=${DATADIR}/logs --workpath=${DATADIR}/work  --serverurl=http://140.221.67.82:8001 --group=kevin_starlord --supported_apps=*

echo "/usr/bin/docker run -d --name awe-client -v /var/run/docker.sock:/var/run/docker.sock -v ${DATADIR}:${DATADIR}  mgrast/awe /gopath/bin/awe-client --data=${DATADIR}/data --logs=${DATADIR}/logs --workpath=${DATADIR}/work  --serverurl=http://140.221.67.82:8001 --group=starlord --supported_apps=*" >> /etc/rc.local
